export const activityData = [
  {
    id: '1',
    image: require('../assets/images/user.jpg'),
    assignee: 'Deepika Gupta',
    desc1: 'updated schedule for',
    assignTo: 'Nitin Shamrao Takras',
    desc2: 'with 100% occupancy till June 30, 2022 in',
    assignedIn: 'Sibros',
    date: 'May 11, 2022',
  },
  {
    id: '2',
    image: require('../assets/images/user.jpg'),
    assignee: 'Deepika Gupta',
    desc1: 'added a new note in',
    assignedIn: 'Sibros',
    date: 'May 11, 2022',
  },
  {
    id: '3',
    image: require('../assets/images/user.jpg'),
    assignee: 'Vinay Kumar',
    desc1: 'submitted a new report titled',
    assignedIn: 'Weekly Report - Team Lead From 25th April to 8th May',
    date: 'May 11, 2022',
  },
  {
    id: '4',
    image: require('../assets/images/user.jpg'),
    assignee: 'Garvita Nagar',
    desc1: 'deactivated employee',
    assignTo: 'Chitransh Shrivastav',
    date: 'May 10, 2022',
  },
  {
    id: '5',
    image: require('../assets/images/user.jpg'),
    assignee: 'Deepika Gupta',
    desc1: 'updated schedule for',
    assignTo: 'Apoorv Bansal',
    desc2: 'with 100% occupancy till May 31, 2022 in',
    assignedIn: 'Icanotes',
    date: 'May 10, 2022',
  },
  {
    id: '6',
    image: require('../assets/images/user.jpg'),
    assignee: 'Irfan Khan',
    desc1: 'submitted a new report titled',
    assignedIn: 'Weekly Report - Sales',
    date: 'May 10, 2022',
  },
  {
    id: '7',
    image: require('../assets/images/user.jpg'),
    assignee: 'Deepika Gupta',
    desc1: 'updated schedule for',
    assignTo: 'Shashank Gautam',
    desc2: 'with 10% occupancy till June 30, 2022 in',
    assignedIn: 'Kutumb',
    date: 'May 10, 2022',
  },
];
