import {createTheme, AllProps as RSAllProps} from '@shopify/restyle';

/**
 * Font families available in this project --
 *  IBMPlexSans-Light.ttf
    IBMPlexSans-SemiBold.ttf
    IBMPlexSans-Regular.ttf
    Inter-VariableFont_slnt,wght.ttf
 */
const palette = {
  indigo: '#4C51BF',
  lightGreyicon: '#A0AEC0',

  // greenLight: '#56DCBA',
  // lightGreen: '#aee35f',
  greenPrimary: '#0ECD9D',
  // greenDark: '#0A906E',

  black: '#393E46',
  zBlack: '#000000',
  halfBlack: 'rgba(0,0,0,0.5)',
  white: '#FFFFFF',
  whiteShade: '#F7F9FD',
  //lightgrey:'#CBD5E0',
  lightGreyBG: '#F7FAFC',

  yellowPrimary: '#fffb2a',
  yellowSecondary: '#fde68a',

  // aliceBlue: '#F4F6F8',

  lightestGrey: '#E2E8F0',
  lightGrey: '#CBD5E0',
  grey: '#888C94',
  mediumGrey: '#5C6677',
  darkGrey: '#4A5568',
  darkestGrey: '#282F3E',
  darkestGrey2: '#222831',

  red: '#E02020',
  lightRed: '#FC8181',
  lighterRed: '#ef7070',
  darkRed: '#99211d',

  lighterblue: '#5A67D8',
  blueDark: '#4C51BF',

  lightBlue: '#63B3ED',
  blue: '#4299E1',
  irisBlue: '#00ADB5',
  // blackText: '#141414',
  // lightBlack: '#191F290F',

  transparent: 'transparent',

  // xyz: 'transparent',

  // green: '#90ce19',
  // darkGreen: '#02af1e',
  limeGreen: '#6ff677',
  lightGreen: '#66de81',
  darkGreen: '#2b6535',

  // disableText: '#555b73',
  // normalText: '#141414',
  // sectionSeperator: '#f6f6f6',
  // audioFileBg: '#f1f1f1',
  // cancelBtnBg: '#a1a1a1',
  // plusButton: '#fb81fd',
  // greenCheck: '#3BB54A',
  // greenShade: '#0DC98F',
  // blumineText: '#343F76',
  // warning: '#FFCC00',
  // messageInputBg: '#F7F7F7',
  // lightingYellow: '#F5AB31',
};

const theme = createTheme({
  colors: {
    primary: palette.indigo,
    iconColorRight: palette.lightGreyicon,
    inactiveColor: palette.halfBlack,
    // lightPrimary: palette.lightBlue,
    // lightBlack: palette.lightBlack,
    // lighterBlue: palette.lighterBlue,
    mainBackground: palette.white,
    lightBackground: palette.white,
    greyBackground: palette.grey,
    lightGreyBackground: palette.lightGrey,
    subTextColor: palette.darkestGrey,
    searchTextColor: palette.darkestGrey2,
    searchIconColor: palette.darkestGrey2,
    searchBackgroundColor: palette.lightGreyBG,
    // bluishBackground: palette.lighterGrey,
    // cardPrimaryBackground: palette.purplePrimary,
    textInputBorderColor: palette.lightGrey,
    dividerBorderColor: palette.lightestGrey,
    textInputBackground: palette.white,
    editBtnBackground: palette.lightBlue,
    deleteBtnBackground: palette.lightRed,
    // aliceBlue: palette.aliceBlue,
    redColor: palette.red,
    lighterRed: palette.lighterRed,
    darkRed: palette.darkRed,
    transparent: palette.transparent,
    // xyz: palette.xyz,
    whiteShade: palette.whiteShade,
    greyText: palette.grey,
    mediumGreyText: palette.mediumGrey,
    whiteText: palette.white,
    darkText: palette.black,
    darkGreyText: palette.darkGrey,
    irisText: palette.irisBlue,
    chipBackground: palette.lightGrey,

    iconColor: palette.darkGrey,
    // success: palette.green,
    // greenShade: palette.greenShade,
    successStep: palette.limeGreen,
    currentStep: palette.yellowPrimary,
    favoriteIconColor: palette.yellowSecondary,
    // inactiveTab: palette.lightGrey,
    // disableText: palette.disableText,
    // normalText: palette.normalText,
    // sectionSeperator: palette.sectionSeperator,
    // audioFileBg: palette.audioFileBg,
    black: palette.black,
    addButtnText: palette.blue,
    // cancelBtnBg: palette.cancelBtnBg,
    // plusButton: palette.plusButton,
    // greenCheck: palette.greenCheck,
    // currency: palette.darkGreen,
    zBlack: palette.zBlack,
    // disabled: palette.greyishBlue,
    // blumineText: palette.blumineText,
    // warning: palette.warning,
    // messageInputBg: palette.messageInputBg,
    // lightingYellow: palette.lightingYellow,
    greenPrimary: palette.greenPrimary,
    lightGreen: palette.lightGreen,
    darkGreen: palette.darkGreen,
    // lightGreen: palette.lightGreen,
    lightRed: palette.lightRed,
    navbarBlue: palette.blueDark,
  },
  spacing: {
    '-xxs': -2,
    '-xs': -4,
    '-sx': -6,
    '-s': -8,
    '-sl': -10,
    '-xm': -12,
    '-m': -16,
    '-ml': -18,
    '-mll': -20,
    '-l': -24,
    '-xl': -30,
    '-ll': -35,
    '-xxl': -40,
    '-xxll': -45,
    '-xxxl': -50,
    '-mxxxl': -55,
    '-mmxxxl': -80,
    none: 0,
    xss: 1,
    xxs: 2,
    xs: 4,
    sx: 6,
    s: 8,
    sl: 10,
    xm: 12,
    bm: 14,
    m: 16,
    ml: 18,
    mll: 20,
    l: 24,
    xl: 30,
    xll: 35,
    xxl: 40,
    xllx: 44,
    xxll: 47,
    xxxl: 50,
    XL: 60,
    XXL: 80,
    XXLL: 90,
    XXXL: 100,
    CXXV: 125,
    CL: 150,
    XXXXL: 200,
    phoneInputPadding: 100,
  },
  breakpoints: {
    phone: 0,
    tablet: 768,
  },
  textInputVariants: {
    error: {
      borderColor: 'redColor',
    },
    phone: {
      paddingLeft: 'phoneInputPadding',
    },
    phoneError: {
      borderColor: 'redColor',
      paddingLeft: 'phoneInputPadding',
    },
    socialError: {
      borderColor: 'redColor',
      paddingLeft: 'XL',
    },
    social: {
      paddingLeft: 'XL',
    },
  },
  textVariants: {
    normalIconText: {
      fontSize: 13,
      fontFamily: 'IBMPlexSans-Light',
    },
    normalText: {
      fontSize: 14,
      fontFamily: 'IBMPlexSans-Light',
    },
    text_2xl: {
      fontSize: 24,
      fontFamily: 'IBMPlexSans-SemiBold',
    },
    text_xl: {
      fontSize: 20,
      fontFamily: 'IBMPlexSans-SemiBold',
    },
    text_Base: {
      fontSize: 16,
      fontFamily: 'IBMPlexSans-Light',
    },
    text_lg: {
      fontSize: 18,
      fontFamily: 'IBMPlexSans-Light',
    },
    text_sm: {
      fontSize: 12,
      fontFamily: 'IBMPlexSans-Light',
    },
    mediumText: {
      fontSize: 14,
      fontFamily: 'IBMPlexSans-SemiBold',
    },
  },
  buttonVariants: {
    secondary: {
      width: '100%',
      height: 43,
      paddingHorizontal: 's',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
      borderColor: 'primary',
      borderWidth: 2,
      backgroundColor: 'mainBackground',
    },
    'secondary-small': {
      width: '100%',
      height: 30,
      paddingHorizontal: 's',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
      borderColor: 'primary',
      borderWidth: 2,
    },
    primary: {
      width: '100%',
      height: 43,
      paddingHorizontal: 's',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
      borderColor: 'primary',
      borderWidth: 2,
    },
    'primary-round': {
      width: '100%',
      height: 50,
      paddingHorizontal: 's',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 27,
      borderColor: 'primary',
      borderWidth: 2,
    },
  },
  buttonTextVariants: {
    primary: {
      color: 'whiteText',
    },
    'primary-round': {
      color: 'whiteText',
    },
    secondary: {
      color: 'primary',
    },
    'secondary-small': {
      fontSize: 12,
      color: 'primary',
    },
  },
  selectBoxVariants: {
    selected: {
      borderColor: 'primary',
      backgroundColor: 'lightPrimary',
    },
    nonSelected: {
      borderColor: 'textInputBorderColor',
    },
    error: {
      borderColor: 'redColor',
    },
  },
  cardVariants: {
    low: {
      overflow: 'visible',
      shadowColor: 'zBlack',
      shadowOpacity: 0.22,
      shadowRadius: 2.22,
      shadowOffset: {width: 0, height: 1},
      elevation: 3,
    },
    medium: {
      overflow: 'visible',
      shadowColor: 'zBlack',
      shadowOpacity: 0.3,
      shadowRadius: 3.84,
      shadowOffset: {width: 0, height: 2},
      elevation: 5,
    },
    high: {
      overflow: 'visible',
      shadowColor: 'zBlack',
      shadowOpacity: 0.29,
      shadowRadius: 4.65,
      shadowOffset: {width: 0, height: 3},
      elevation: 7,
    },
  },
});
export type Theme = typeof theme;
export type AllProps = RSAllProps<Theme>;
export default theme;
