# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

# platform :ios do
#   desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#   end
# end

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    answer = UI.select("Would you like to add a Changelog?", ["Yes", "No"])
    changelog = ask('Type Changelog message:') if answer == "Yes"

    match(type: 'appstore')
    increment_build_number(xcodeproj: "kutumb.xcodeproj")
    # increment_version_number(
    #   bump_type: "patch",
    #   xcodeproj: "kutumb.xcodeproj"
    # )
    build_app(workspace: "kutumb.xcworkspace", scheme: "kutumb")
    if changelog
      upload_to_testflight(changelog: changelog,demo_account_required: false)
    else
      upload_to_testflight
    end  
  end
end